# Generated by Django 4.0.5 on 2022-07-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='home name')),
                ('about', models.TextField(verbose_name='home about')),
                ('image', models.ImageField(upload_to='media', verbose_name='home img')),
            ],
        ),
    ]
