# Generated by Django 4.0.5 on 2022-07-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_home_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='media', verbose_name='logo img')),
            ],
        ),
        migrations.RemoveField(
            model_name='home',
            name='logo',
        ),
    ]
