# Generated by Django 4.0.5 on 2022-07-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_logo_remove_home_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logo',
            old_name='logo',
            new_name='image',
        ),
        migrations.AddField(
            model_name='logo',
            name='name',
            field=models.CharField(default=1, max_length=30, verbose_name='logo name'),
            preserve_default=False,
        ),
    ]
