# Generated by Django 4.0.5 on 2022-07-03 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_logo_logo_image_logo_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='logo',
        ),
    ]
