# Generated by Django 4.0.5 on 2022-07-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_service1'),
    ]

    operations = [
        migrations.CreateModel(
            name='crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='crypto name')),
                ('name1', models.CharField(max_length=200, verbose_name='crypto name1')),
                ('name2', models.CharField(max_length=200, verbose_name='crypto name2')),
                ('about', models.TextField(verbose_name='crypto about')),
                ('about1', models.TextField(verbose_name='crypto about1')),
                ('about2', models.TextField(verbose_name='crypto about2')),
                ('image', models.ImageField(upload_to='media', verbose_name='crypto img')),
            ],
        ),
    ]
