# Generated by Django 4.0.5 on 2022-07-04 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_crypto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crypto',
            name='name1',
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='name2',
        ),
    ]
