# Generated by Django 4.0.5 on 2022-07-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_crypto_about2'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='about name')),
                ('about', models.TextField(verbose_name='about')),
                ('image', models.ImageField(upload_to='media', verbose_name='about img')),
            ],
        ),
    ]
