# Generated by Django 4.0.5 on 2022-07-04 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='image',
        ),
    ]
