# Generated by Django 4.0.5 on 2022-07-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='home1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='home name')),
                ('about', models.TextField(verbose_name='home about')),
                ('name1', models.CharField(max_length=200, verbose_name='home name1')),
                ('about1', models.TextField(verbose_name='home about1')),
                ('name2', models.CharField(max_length=200, verbose_name='home name2')),
                ('about2', models.TextField(verbose_name='home about2')),
                ('name3', models.CharField(max_length=200, verbose_name='home name3')),
                ('about3', models.TextField(verbose_name='home about3')),
                ('name4', models.CharField(max_length=200, verbose_name='home name4')),
                ('about4', models.TextField(verbose_name='home about4')),
                ('name5', models.CharField(max_length=200, verbose_name='home name5')),
                ('about5', models.TextField(verbose_name='home about5')),
            ],
        ),
    ]
