# Generated by Django 4.0.5 on 2022-07-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_home1'),
    ]

    operations = [
        migrations.CreateModel(
            name='hometest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='hometest name')),
                ('about', models.TextField(verbose_name='hometest about')),
                ('image', models.ImageField(upload_to='media', verbose_name='hometest img')),
            ],
        ),
    ]
