# Generated by Django 4.0.5 on 2022-07-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_hometest'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='about2',
            field=models.TextField(default=1, verbose_name='crypto about2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crypto',
            name='image1',
            field=models.ImageField(default=1, upload_to='media', verbose_name='crypto img1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crypto',
            name='image2',
            field=models.ImageField(default=1, upload_to='media', verbose_name='crypto img2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crypto',
            name='name1',
            field=models.CharField(default=1, max_length=200, verbose_name='crypto name1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crypto',
            name='name2',
            field=models.CharField(default=1, max_length=200, verbose_name='crypto name2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crypto',
            name='text',
            field=models.TextField(default=1, verbose_name='crypto text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crypto',
            name='text1',
            field=models.TextField(default=1, verbose_name='crypto text1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crypto',
            name='text2',
            field=models.TextField(default=1, verbose_name='crypto text2'),
            preserve_default=False,
        ),
    ]
